"""empty message

Revision ID: 66485bbf778b
Revises: 47d55fc309b4
Create Date: 2023-12-03 00:48:49.500748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66485bbf778b'
down_revision = '47d55fc309b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_code', sa.String(length=6), nullable=True))
        batch_op.create_unique_constraint(None, ['bill_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('bill_code')

    # ### end Alembic commands ###
