"""empty message

Revision ID: 6f34d1b7ae88
Revises: 9bdff9fcf059
Create Date: 2023-12-24 22:02:20.199194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f34d1b7ae88'
down_revision = '9bdff9fcf059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('drink')
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=5), nullable=True))

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_cost', sa.Integer(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bill_id')

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('ticket_cost')

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.drop_column('position')

    op.create_table('drink',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='drink_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('movie_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='review_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
